Feature: Retry Attribute Generation
    As A Test Author
    I Want The Retry Attribute To Be Automatically Added To Generated Tests
    So That Flaky Tests Are Retried Automatically

Scenario: Retry Attribute Is Added To Generated Test Method
    Given The Test Method Is Generated By Reqnroll
    When  The Test Executes
    Then  The Test Should Pass
