Feature: Retry Outcomes
    As A Test Author
    I Want Only Tests That Fail With A Test Error To Be Retried
    So That Other Outcomes Are Reported Straight Away, And Failing Tests Are Not Retried Forever

Scenario: Test Failing On Every Attempt Is Retried Until No Retries Are Left
    Given The Test Fails On Every Attempt
    When  The Test Executes
    Then  The Test Should Not Run

@ignore
Scenario: Ignored Test Is Skipped
    Given The Test Method Is Generated By Reqnroll
    When  The Test Executes
    Then  The Test Should Not Run

Scenario: Test Skipped At Runtime Is Not Retried
    Given The Test Is Skipped At Runtime
    When  The Test Executes
    Then  The Test Should Not Run

Scenario: Pending Test Is Not Retried
    Given The Test Is Pending
    When  The Test Executes
    Then  The Test Should Not Run

Scenario: Cancelled Test Is Not Retried
    Given The Test Run Is Cancelled
    When  The Test Executes
    Then  The Test Should Not Run
