Feature: Skipped Tests
    As A Test Author
    I Want Skipped Tests To Stay Skipped
    So That They Are Neither Retried Nor Reported As Failures

@ignore
Scenario: Ignored Test Is Skipped
    Given The Test Method Is Generated By Reqnroll
    When  The Test Executes
    Then  The Test Should Not Run

Scenario: Test Skipped At Runtime Is Skipped
    Given The Test Is Skipped At Runtime
    When  The Test Executes
    Then  The Test Should Not Run
