namespace Reqnroll.Retry.xUnit.Tests;

/// <summary>
///     Tests that verify the retry logic is correctly added to generated Reqnroll test methods, without replacing the xUnit attributes generated by Reqnroll.
/// </summary>
public sealed class RetryAttributeGenerationTests
{
    private const string GeneratedFeatureClassName = "RetryAttributeGenerationFeature";
    private const string ReqnrollRetryCountKey = "ReqnrollRetryCount";

    internal static int ExpectedRetryCount => int.Parse
    (
        typeof(RetryAttributeGenerationTests).Assembly
            .GetCustomAttributes<AssemblyMetadataAttribute>()
            .SingleOrDefault(attribute => attribute.Key == ReqnrollRetryCountKey)?.Value ?? "1"
    );

    [Fact]
    public void Generated_Test_Methods_Should_Keep_Reqnroll_Attributes()
    {
        Type? featureType = typeof(RetryAttributeGenerationTests).Assembly.GetTypes().SingleOrDefault(type => type.Name == GeneratedFeatureClassName);

        Assert.NotNull(featureType);

        if (featureType is null) return;

        FactAttribute[] testAttributes = featureType.GetMethods(BindingFlags.Public | BindingFlags.Instance)
            .Select(method => method.GetCustomAttribute<FactAttribute>()).OfType<FactAttribute>().ToArray();

        Assert.NotEmpty(testAttributes);

        // The Retry Logic Must Not Replace The Attributes Generated By Reqnroll, Which Reqnroll Relies On To Skip Ignored Tests
        Assert.All(testAttributes, attribute => Assert.True(attribute.GetType() == typeof(FactAttribute) || attribute.GetType() == typeof(TheoryAttribute), $"Expected [{nameof(FactAttribute)}] or [{nameof(TheoryAttribute)}], But Found [{attribute.GetType().Name}]."));
    }
}
