namespace Reqnroll.Retry.xUnit.Tests;

/// <summary>
///     Tests that verify the retry logic is correctly added to generated Reqnroll test methods, without replacing the xUnit attributes generated by Reqnroll.
/// </summary>
public sealed class RetryAttributeGenerationTests
{
    private const string GeneratedFeatureClassName = "RetryAttributeGenerationFeature";
    private const string GeneratedFeatureFileName = "RetryAttribute.feature.cs";
    private const string ReqnrollRetryCountKey = "ReqnrollRetryCount";

    internal static int ExpectedRetryCount => int.Parse
    (
        typeof(RetryAttributeGenerationTests).Assembly
            .GetCustomAttributes<AssemblyMetadataAttribute>()
            .SingleOrDefault(attribute => attribute.Key == ReqnrollRetryCountKey)?.Value ?? "1"
    );

    [Fact]
    public void Generated_Test_Methods_Should_Keep_Reqnroll_Attributes()
    {
        Type? featureType = typeof(RetryAttributeGenerationTests).Assembly.GetTypes().SingleOrDefault(type => type.Name == GeneratedFeatureClassName);

        Assert.NotNull(featureType);

        if (featureType is null) return;

        FactAttribute[] testAttributes = featureType.GetMethods(BindingFlags.Public | BindingFlags.Instance)
            .Select(method => method.GetCustomAttribute<FactAttribute>()).OfType<FactAttribute>().ToArray();

        Assert.NotEmpty(testAttributes);

        // The Retry Logic Must Not Replace The Attributes Generated By Reqnroll, Which Reqnroll Relies On To Skip Ignored Tests
        Assert.All(testAttributes, attribute => Assert.True(attribute.GetType() == typeof(FactAttribute) || attribute.GetType() == typeof(TheoryAttribute), $"Expected [{nameof(FactAttribute)}] or [{nameof(TheoryAttribute)}], But Found [{attribute.GetType().Name}]."));
    }

    [Fact]
    public void Generated_Feature_Code_File_Should_Contain_Retry_Loop()
    {
        string? projectDirectory = Path.GetDirectoryName(typeof(RetryAttributeGenerationTests).Assembly.Location);

        Assert.NotNull(projectDirectory);

        if (projectDirectory is null) return;

        DirectoryInfo? directory = new (projectDirectory);

        while (directory is not null && File.Exists(Path.Combine(directory.FullName, "Reqnroll.Retry.xUnit.Tests.csproj")) is false)
        {
            directory = directory.Parent;
        }

        Assert.NotNull(directory);

        if (directory is null) return;

        string featuresDirectory = Path.Combine(directory.FullName, "Features");
        string generatedFilePath = Path.Combine(featuresDirectory, GeneratedFeatureFileName);

        Assert.True(File.Exists(generatedFilePath), $"Expected generated file to exist at: {generatedFilePath}.");

        string generatedCode = File.ReadAllText(generatedFilePath);

        // The Initial Attempt Plus One Attempt Per Retry
        string maximumAttempts = (ExpectedRetryCount + 1).ToString();

        Assert.True(generatedCode.Contains($"__attempt <= {maximumAttempts})"), $"Expected generated code to contain a retry loop with a maximum of {maximumAttempts} attempts.");
    }
}
