Feature: Retry Attribute Generation
    As a test author
    I want the Retry attribute to be automatically added to generated tests
    So that flaky tests are retried automatically

Scenario: Retry attribute is added to generated test method
    Given the test method is generated by Reqnroll
    When the test executes
    Then the test should pass
