namespace Reqnroll.Retry.MSTest.Tests.StepBindings;

[Binding]
public sealed class RetryAttributeSteps
{
    [Given("The Test Method Is Generated By Reqnroll")]
    public void The_Test_Method_Is_Generated_By_Reqnroll()
    {
        // This Step Exists To Verify Code Generation Works
    }

    [When("The Test Executes")]
    public void The_Test_Executes()
    {
        // This Step Exists To Verify The Test Runs
    }

    [Then("The Test Should Pass")]
    public void The_Test_Should_Pass()
    {
        // This Step Exists To Verify The Test Completes Successfully
    }
}
