namespace Reqnroll.Retry.NUnit.Tests.StepBindings;

[Binding]
public sealed class RetryAttributeSteps
{
    private static int _attemptCount;

    [Given("The Test Method Is Generated By Reqnroll")]
    public void The_Test_Method_Is_Generated_By_Reqnroll()
    {
        // This Step Exists To Verify Code Generation Works
    }

    [Given("The Test Fails Until The Final Retry")]
    public void The_Test_Fails_Until_The_Final_Retry()
    {
        // Fail The Initial Attempt And Every Retry Except The Last One, So The Test Only Passes If Every Configured Retry Is Made
        int attempt = Interlocked.Increment(ref _attemptCount);

        // NUnit Only Retries Assertion Failures, Not Unexpected Exceptions
        if (attempt <= RetryAttributeGenerationTests.ExpectedRetryCount)
        {
            Assert.Fail($"Simulated Transient Failure On Attempt {attempt}.");
        }
    }

    [When("The Test Executes")]
    public void The_Test_Executes()
    {
        // This Step Exists To Verify The Test Runs
    }

    [Then("The Test Should Pass")]
    public void The_Test_Should_Pass()
    {
        // This Step Exists To Verify The Test Completes Successfully
    }
}
