namespace Reqnroll.Retry.NUnit.Tests.StepBindings;

[Binding]
public sealed class RetryAttributeSteps
{
    [Given("the test method is generated by Reqnroll")]
    public void Given_The_Test_Method_Is_Generated_By_Reqnroll()
    {
        // This Step Exists To Verify Code Generation Works
    }

    [When("the test executes")]
    public void When_The_Test_Executes()
    {
        // This Step Exists To Verify The Test Runs
    }

    [Then("the test should pass")]
    public void Then_The_Test_Should_Pass()
    {
        // This Step Exists To Verify The Test Completes Successfully
    }
}
