Feature: Retry Attribute Generation
    As A Test Author
    I Want The Retry Attribute To Be Automatically Added To Generated Tests
    So That Flaky Tests Are Retried Automatically

Scenario: Retry Attribute Is Added To Generated Test Method
    Given The Test Method Is Generated By Reqnroll
    When  The Test Executes
    Then  The Test Should Pass

Scenario: Failing Test Is Retried Until It Passes
    Given The Test Fails Until The Final Retry
    When  The Test Executes
    Then  The Test Should Pass
