[assembly: GeneratorPlugin(typeof(Reqnroll.Retry.xUnit.GeneratorPlugin))]

namespace Reqnroll.Retry.xUnit;

/// <summary>
///     A Reqnroll generator plugin that adds retry functionality to all generated BDD test methods.
///     The retry count can be configured via the "ReqnrollRetryCount" property in the project file.
/// </summary>
/// <remarks>
///     xUnit does not have a native retry attribute, so this plugin wraps the body of each generated test method in a retry loop instead.
///     This keeps the plugin free of dependencies, and leaves the test attributes generated by Reqnroll untouched, so ignored and skipped tests keep working.
///     Both xUnit v2 (Reqnroll.xUnit) and xUnit v3 (Reqnroll.xunit.v3) are supported.
/// </remarks>
public sealed class GeneratorPlugin : IGeneratorPlugin
{
    private const string RetryCountParameter = "RetryCount";
    private const int DefaultRetryCount = 1;

    public void Initialize(GeneratorPluginEvents generatorPluginEvents, GeneratorPluginParameters generatorPluginParameters, UnitTestProviderConfiguration unitTestProviderConfiguration)
    {
        int retryCount = GetRetryCount(generatorPluginParameters);

        // A Retry Count Of 0 Disables Retries
        if (retryCount == 0) return;

        generatorPluginEvents.RegisterDependencies += (sender, eventArguments) =>
        {
            eventArguments.ObjectContainer.RegisterFactoryAs<IFeatureGeneratorProvider>
            (
                container => new RetryFeatureGeneratorProvider
                (
                    new RetryFeatureGenerator
                    (
                        container.Resolve<IUnitTestGeneratorProvider>(),
                        container.Resolve<CodeDomHelper>(),
                        container.Resolve<ReqnrollConfiguration>(),
                        container.Resolve<IDecoratorRegistry>(),
                        retryCount
                    )
                ), "retry"
            );
        };
    }

    private static int GetRetryCount(GeneratorPluginParameters generatorPluginParameters)
    {
        IDictionary<string, string> parameters = generatorPluginParameters.GetParametersAsDictionary();

        if (parameters.TryGetValue(RetryCountParameter, out string? retryCountString) is false) return DefaultRetryCount;

        return int.TryParse(retryCountString, out int retryCount) && retryCount >= 0
            ? retryCount
            : throw new ReqnrollException($@"The ""{RetryCountParameter}"" parameter must be a whole number of 0 or more, but is ""{retryCountString}"".");
    }
}
