[assembly: GeneratorPlugin(typeof(Reqnroll.Retry.xUnit.GeneratorPlugin))]

namespace Reqnroll.Retry.xUnit;

/// <summary>
///     A Reqnroll generator plugin that adds retry functionality to all generated BDD test methods.
///     The retry count can be configured via the "ReqnrollRetryCount" property in the project file.
/// </summary>
/// <remarks>
///     xUnit does not have a native retry attribute, so this plugin wraps the body of each generated test method in a retry loop instead.
///     This keeps the plugin free of dependencies, and leaves the SkippableFact/SkippableTheory attributes generated by Reqnroll untouched, so ignored and skipped tests keep working.
/// </remarks>
public sealed class GeneratorPlugin : IGeneratorPlugin
{
    private const string RetryCountParameter = "RetryCount";
    private const int DefaultRetryCount = 1;

    public void Initialize(GeneratorPluginEvents generatorPluginEvents, GeneratorPluginParameters generatorPluginParameters, UnitTestProviderConfiguration unitTestProviderConfiguration)
    {
        int retryCount = GetRetryCount(generatorPluginParameters);

        generatorPluginEvents.RegisterDependencies += (sender, eventArguments) =>
        {
            eventArguments.ObjectContainer.RegisterFactoryAs<IFeatureGeneratorProvider>
            (
                container => new RetryFeatureGeneratorProvider
                (
                    new RetryFeatureGenerator
                    (
                        container.Resolve<IUnitTestGeneratorProvider>(),
                        container.Resolve<CodeDomHelper>(),
                        container.Resolve<ReqnrollConfiguration>(),
                        container.Resolve<IDecoratorRegistry>(),
                        retryCount
                    )
                ), "retry"
            );
        };
    }

    private static int GetRetryCount(GeneratorPluginParameters generatorPluginParameters)
    {
        IDictionary<string, string> parameters = generatorPluginParameters.GetParametersAsDictionary();

        return parameters.TryGetValue(RetryCountParameter, out string? retryCountString) && int.TryParse(retryCountString, out int retryCount) && retryCount > 0
            ? retryCount
            : DefaultRetryCount;
    }
}
