namespace Reqnroll.Retry.xUnit;

/// <summary>
///     A feature generator that wraps the body of every generated xUnit test method in a retry loop.
///     This enables automatic retry functionality for BDD scenarios.
/// </summary>
/// <remarks>
///     Reqnroll generates the body of a test method after the test method decorators have run, so the retry loop is added once the whole test class has been generated.
///     After a failed attempt, the test runner is torn down and initialised again, the same way xUnit does it between tests, before the scenario runs again.
///     Only test errors are retried. Skipped, pending, and undefined steps, and binding errors, fail the same way on every attempt, so they are reported straight away.
///     Once all retries have been used up, the test fails with the exception of the final attempt.
///     Both xUnit v2 (Reqnroll.xUnit) and xUnit v3 (Reqnroll.xunit.v3) are supported, but only xUnit v3 lets a test know that the test run is being cancelled, in which case it is not retried either.
///     This derives from <see cref="UnitTestFeatureGenerator" /> because Reqnroll only passes the feature file details, which are needed for Cucumber messages, to generators of that type.
/// </remarks>
public sealed class RetryFeatureGenerator(IUnitTestGeneratorProvider testGeneratorProvider, CodeDomHelper codeDomHelper, ReqnrollConfiguration reqnrollConfiguration, IDecoratorRegistry decoratorRegistry, int retryCount)
    : UnitTestFeatureGenerator(testGeneratorProvider, codeDomHelper, reqnrollConfiguration, decoratorRegistry), IFeatureGenerator
{
    private const string TestOutputHelperField = "_testOutputHelper";
    private const string TestContextType = "Xunit.TestContext";
    private const string TestContextCurrentProperty = "Current";
    private const string TestContextCancellationTokenProperty = "CancellationToken";
    private const string AttemptVariable = "__attempt";
    private const string ExceptionVariable = "__exception";
    private const string RetryMessageFormat = "Attempt {0} Of {1} Failed, Retrying: {2}";

    // The Test Attributes Generated By Reqnroll, Mapped To The Version Of xUnit That Generates Them
    private static readonly Dictionary<string, XunitVersion> XunitVersionsByTestAttribute = new ()
    {
        ["Xunit.SkippableFactAttribute"] = XunitVersion.V2,
        ["Xunit.SkippableTheoryAttribute"] = XunitVersion.V2,
        ["Xunit.FactAttribute"] = XunitVersion.V3,
        ["Xunit.TheoryAttribute"] = XunitVersion.V3
    };

    private CodeDomHelper CodeDomHelper { get; } = codeDomHelper;

    private int RetryCount { get; } = retryCount;

    // Re-Implements The Interface Method, Because The Base Class Method Is Not Virtual
    public new UnitTestFeatureGenerationResult GenerateUnitTestFixture(ReqnrollDocument document, string testClassName, string targetNamespace)
    {
        UnitTestFeatureGenerationResult generationResult = base.GenerateUnitTestFixture(document, testClassName, targetNamespace);

        IEnumerable<CodeMemberMethod> methods = generationResult.CodeNamespace.Types.Cast<CodeTypeDeclaration>()
            .SelectMany(testClass => testClass.Members.OfType<CodeMemberMethod>());

        foreach (CodeMemberMethod method in methods)
        {
            XunitVersion? xunitVersion = GetXunitVersion(method);

            // Only Test Methods Have A Test Attribute, And Therefore An xUnit Version
            if (xunitVersion is not null)
            {
                AddRetryLoop(method, xunitVersion.Value);
            }
        }

        return generationResult;
    }

    private static XunitVersion? GetXunitVersion(CodeMemberMethod method) => method.CustomAttributes.Cast<CodeAttributeDeclaration>()
        .Select(attribute => XunitVersionsByTestAttribute.TryGetValue(attribute.Name, out XunitVersion xunitVersion) ? xunitVersion : (XunitVersion?) null)
        .FirstOrDefault(xunitVersion => xunitVersion is not null);

    private void AddRetryLoop(CodeMemberMethod testMethod, XunitVersion xunitVersion)
    {
        // The Initial Attempt Plus One Attempt Per Retry
        CodePrimitiveExpression maximumAttempts = new (RetryCount + 1);

        CodeVariableReferenceExpression attempt = new (AttemptVariable);

        // Rethrow The Failure When It Should Not Be Retried, Otherwise Log The Failure And Reset The Test Runner Before The Next Attempt
        CodeCatchClause retryClause = new
        (
            ExceptionVariable, new CodeTypeReference(typeof(Exception), CodeTypeReferenceOptions.GlobalReference),
            new CodeConditionStatement(CreateRethrowCondition(attempt, maximumAttempts, xunitVersion), new CodeThrowExceptionStatement()),
            new CodeExpressionStatement
            (
                new CodeMethodInvokeExpression
                (
                    new CodeFieldReferenceExpression(new CodeThisReferenceExpression(), TestOutputHelperField), "WriteLine",
                    new CodePrimitiveExpression(RetryMessageFormat), attempt, maximumAttempts, new CodePropertyReferenceExpression(new CodeVariableReferenceExpression(ExceptionVariable), nameof(Exception.Message))
                )
            ),
            CreateAwaitStatement(GeneratorConstants.TEST_CLEANUP_NAME),
            CreateAwaitStatement(GeneratorConstants.TEST_INITIALIZE_NAME)
        );

        // Return As Soon As An Attempt Passes
        CodeStatement[] attemptStatements = testMethod.Statements.Cast<CodeStatement>().Append(new CodeMethodReturnStatement()).ToArray();

        CodeTryCatchFinallyStatement attemptBlock = new (attemptStatements, [retryClause]);

        CodeIterationStatement retryLoop = new
        (
            new CodeVariableDeclarationStatement(typeof(int), AttemptVariable, new CodePrimitiveExpression(1)),
            new CodeBinaryOperatorExpression(attempt, CodeBinaryOperatorType.LessThanOrEqual, maximumAttempts),
            new CodeAssignStatement(attempt, new CodeBinaryOperatorExpression(attempt, CodeBinaryOperatorType.Add, new CodePrimitiveExpression(1))),
            attemptBlock
        );

        testMethod.Statements.Clear();
        testMethod.Statements.Add(retryLoop);
    }

    private static CodeExpression CreateRethrowCondition(CodeExpression attempt, CodeExpression maximumAttempts, XunitVersion xunitVersion)
    {
        CodePropertyReferenceExpression scenarioContext = new (new CodeFieldReferenceExpression(new CodeThisReferenceExpression(), GeneratorConstants.TESTRUNNER_FIELD), nameof(ITestRunner.ScenarioContext));

        CodePropertyReferenceExpression executionStatus = new (scenarioContext, nameof(ScenarioContext.ScenarioExecutionStatus));

        CodeFieldReferenceExpression testError = new (new CodeTypeReferenceExpression(new CodeTypeReference(typeof(ScenarioExecutionStatus), CodeTypeReferenceOptions.GlobalReference)), nameof(ScenarioExecutionStatus.TestError));

        List<CodeExpression> conditions =
        [
            // No Retries Are Left
            new CodeBinaryOperatorExpression(attempt, CodeBinaryOperatorType.ValueEquality, maximumAttempts),

            // The Scenario Failed Before It Was Initialised
            new CodeBinaryOperatorExpression(scenarioContext, CodeBinaryOperatorType.IdentityEquality, new CodePrimitiveExpression(null)),

            // The Scenario Did Not Fail With A Test Error, But Was Skipped, Pending, Undefined, Or Had A Binding Error, Which Would Not Change On Another Attempt
            new CodeBinaryOperatorExpression(new CodeBinaryOperatorExpression(executionStatus, CodeBinaryOperatorType.ValueEquality, testError), CodeBinaryOperatorType.ValueEquality, new CodePrimitiveExpression(false))
        ];

        if (xunitVersion is XunitVersion.V3)
        {
            // The Test Run Is Being Cancelled
            conditions.Add
            (
                new CodePropertyReferenceExpression
                (
                    new CodePropertyReferenceExpression
                    (
                        new CodePropertyReferenceExpression(new CodeTypeReferenceExpression(new CodeTypeReference(TestContextType, CodeTypeReferenceOptions.GlobalReference)), TestContextCurrentProperty), TestContextCancellationTokenProperty
                    ),
                    nameof(CancellationToken.IsCancellationRequested)
                )
            );
        }

        return conditions.Aggregate((left, right) => new CodeBinaryOperatorExpression(left, CodeBinaryOperatorType.BooleanOr, right));
    }

    private CodeExpressionStatement CreateAwaitStatement(string methodName) => new
    (
        CodeDomHelper.MarkCodeMethodInvokeExpressionAsAwait(new CodeMethodInvokeExpression(new CodeThisReferenceExpression(), methodName))
    );

    private enum XunitVersion
    {
        V2,
        V3
    }
}
