namespace Reqnroll.Retry.xUnit.Tests.StepBindings;

[Binding]
public sealed class RetryAttributeSteps(IUnitTestRuntimeProvider unitTestRuntimeProvider)
{
    private static int _attemptCount;
    private static int _runtimeSkipCount;

    internal static int RuntimeSkipCount => _runtimeSkipCount;

    [Given("The Test Method Is Generated By Reqnroll")]
    public void The_Test_Method_Is_Generated_By_Reqnroll()
    {
        // This Step Exists To Verify Code Generation Works
    }

    [Given("The Test Fails Until The Final Retry")]
    public void The_Test_Fails_Until_The_Final_Retry()
    {
        // Fail The Initial Attempt And Every Retry Except The Last One, So The Test Only Passes If Every Configured Retry Is Made
        int attempt = Interlocked.Increment(ref _attemptCount);

        if (attempt <= RetryAttributeGenerationTests.ExpectedRetryCount)
        {
            throw new InvalidOperationException($"Simulated Transient Failure On Attempt {attempt}.");
        }
    }

    [Given("The Test Is Skipped At Runtime")]
    public void The_Test_Is_Skipped_At_Runtime()
    {
        // Count The Attempts, So The Test Can Verify That A Skipped Test Is Not Retried
        Interlocked.Increment(ref _runtimeSkipCount);

        unitTestRuntimeProvider.TestIgnore("This Test Is Skipped At Runtime, So It Should Be Reported As Skipped Rather Than Retried");
    }

    [When("The Test Executes")]
    public void The_Test_Executes()
    {
        // This Step Exists To Verify The Test Runs
    }

    [Then("The Test Should Pass")]
    public void The_Test_Should_Pass()
    {
        // This Step Exists To Verify The Test Completes Successfully
    }

    [Then("The Test Should Not Run")]
    public void The_Test_Should_Not_Run()
    {
        throw new InvalidOperationException("This Step Should Never Execute, Because The Test Should Have Been Skipped.");
    }
}
