namespace Reqnroll.Retry.xUnit.Tests.StepBindings;

[Binding]
public sealed class RetryAttributeSteps(IUnitTestRuntimeProvider unitTestRuntimeProvider)
{
    private static readonly ConcurrentDictionary<string, int> AttemptCounts = new ();

    // The Number Of Times A Step Has Run, So Tests Can Verify How Many Attempts A Scenario Was Given
    internal static int GetAttemptCount(string step) => AttemptCounts.TryGetValue(step, out int attemptCount) ? attemptCount : 0;

    [Given("The Test Method Is Generated By Reqnroll")]
    public void The_Test_Method_Is_Generated_By_Reqnroll()
    {
        // This Step Exists To Verify Code Generation Works
    }

    [Given("The Test Fails Until The Final Retry")]
    public void The_Test_Fails_Until_The_Final_Retry()
    {
        // Fail The Initial Attempt And Every Retry Except The Last One, So The Test Only Passes If Every Configured Retry Is Made
        int attempt = CountAttempt();

        if (attempt <= RetryAttributeGenerationTests.ExpectedRetryCount)
        {
            throw new InvalidOperationException($"Simulated Transient Failure On Attempt {attempt}.");
        }
    }

    [Given("The Test Fails On Every Attempt")]
    public void The_Test_Fails_On_Every_Attempt()
    {
        throw new InvalidOperationException($"Simulated Persistent Failure On Attempt {CountAttempt()}.");
    }

    [Given("The Test Is Skipped At Runtime")]
    public void The_Test_Is_Skipped_At_Runtime()
    {
        CountAttempt();

        unitTestRuntimeProvider.TestIgnore("This Test Is Skipped At Runtime, So It Should Be Reported As Skipped Rather Than Retried");
    }

    [Given("The Test Is Pending")]
    public void The_Test_Is_Pending()
    {
        CountAttempt();

        throw new PendingStepException();
    }

    [Given("The Test Run Is Cancelled")]
    public void The_Test_Run_Is_Cancelled()
    {
        CountAttempt();

        TestContext.Current.CancelCurrentTest();

        throw new OperationCanceledException(TestContext.Current.CancellationToken);
    }

    [When("The Test Executes")]
    public void The_Test_Executes()
    {
        // This Step Exists To Verify The Test Runs
    }

    [Then("The Test Should Pass")]
    public void The_Test_Should_Pass()
    {
        // This Step Exists To Verify The Test Completes Successfully
    }

    [Then("The Test Should Not Run")]
    public void The_Test_Should_Not_Run()
    {
        throw new InvalidOperationException("This Step Should Never Execute, Because The Test Should Have Been Skipped Or Failed Before It.");
    }

    private static int CountAttempt([CallerMemberName] string step = "") => AttemptCounts.AddOrUpdate(step, 1, (_, attemptCount) => attemptCount + 1);
}
